sudo: required
dist: trusty
language: python

python:
  - "3.5"

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update --fix-missing

install:
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install -y libpulse-dev
  - pip install -r requirements-dev.txt

script: python3 -m pytest tests