language: python
python:
  - "3.5"
install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip nose
  - pip install coveralls

script: noseteset ./tests --with-coverage --cover-package=./joytan