language: python

python:
  - "3.5"

before_install:
  - sudo apt-get install libpulse-dev

install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls

script: nosetests ./tests --with-coverage --cover-package=./joytan